### ISSUE TITLE
Balena preloaded image exceeds maximum Github upload limit of 2048Mbs

### ISSUE THREAD

**Issue by luandro** [digidem/edt-offline#41]
**Describe the bug**

Full logs: https://github.com/digidem/edt-offline/commit/b655a48786e1baf8516f5931a8550d5eba82dd46/checks/12200298288/logs

```
-> Uploading release artifacts
  Uploading: artifacts/generic-aarch64-v0.4.3.tar.gz
  Uploading: artifacts/generic-amd64-v0.4.3.tar.gz
  Error: File size (2285701261) is greater than possible Buffer: 2147483647 bytes
  (node:1853) UnhandledPromiseRejectionWarning: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2285701261) is greater than possible Buffer: 2147483647 bytes
      at tryCreateBuffer (fs.js:339:13)
      at Object.readFileSync (fs.js:375:14)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:583556
      at Generator.next (<anonymous>)
      at s (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:582729)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  (node:1853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:1853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ```

**To Reproduce**
Push a git tag in order to trigger the release workflow.

**Expected behavior**
Action should be able to generate several artifacts and upload them as Github release.

**Additional context**

**Possible Solution**
~~https://github.com/actions/upload-artifact/issues/59~~ Problem isn't with artifact size, but with upload limit for release binaries.

Only possible solution might be to use [s3-file-upload action](https://github.com/marketplace/actions/s3-file-upload) with self-hosted minio, amazon s3 or digitla ocean spaces.

**Comment by luandro** [comment]
Solved by 3d7cb14
